# Generated by Django 5.1 on 2024-08-16 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sheduler', '0002_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='event_sheduler.events'),
        ),
    ]
